{
  "services":
    {
      "electron":
        {
          "env_file": ["./.env"],
          "environment": { "PORT": "${ELECTRON_PORT:-8080}" },
          "image": "ghcr.io/kk-spartans/electron/electron-app:latest",
          "ports": ["${ELECTRON_PORT:-8080}:8080"],
          "restart": "unless-stopped",
        },
    },
}
