name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Release
        run: |
          nix profile add nixpkgs#devenv
          devenv tasks run electron:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
